package com.az;

public class ManifestHeader {
	public static String[] HEADER = {"Source System",
		"Title",
		"Classification",
		"Security",
		"Record Form",
		"Author",
		"Date Created",
		"Language",
		"Relative Path",
		"Date Closed",
		"File Name",
		"Event Trigger",
		"Legal Hold Name",
		"Product",
		"Substance Reference",
		"Physical Location Description",
		"Signer",
		"Signer ID",
		"Signature Method",
		"Signature Value",
		"Signature Encoding",
		"Signature Public Key",
		"Signature Date",
		"Adverse Event Report No",
		"AstraZeneca Site",
		"Audience",
		"Audit Records",
		"Authenticity Comments",
		"Authenticity Standard",
		"Authority Reference No",
		"Batch No",
		"Contract No ",
		"Country",
		"Department",
		"Dosage Form",
		"Drawing No",
		"Drug Product ID",
		"Drug Substance No",
		"Employee Name",
		"Employee No",
		"Engineer",
		"Equipment ID",
		"Healthcare Professional",
		"Intermediate Product Code",
		"Investigational Site",
		"Investigator",
		"Laboratory Notebook No",
		"Marketing Company",
		"Notes",
		"Legacy Record Number",
		"Original Location",
		"Patent ID",
		"Patient",
		"Physical Location Reference",
		"Policy No",
		"Promotional ID",
		"Sales Representative",
		"Signature Validation",
		"SOP No",
		"Study Code",
		"Subject",
		"System ID",
		"Tax Year",
		"Therapeutic Area",
		"Vendor"};

}
